name: rnamigos
channels:
  - anaconda
  - bioconda
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - absl-py
  - biopython
  - blas
  - blinker
  - brotlipy
  - c-ares
  - ca-certificates
  - cachetools
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - cryptography
  - cycler
  - decorator
  - dgl
  - fontconfig
  - freetype
  - gettext
  - glib
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - icu
  - idna
  - importlib-metadata
  - intel-openmp
  - kiwisolver
  - libcxx
  - libedit
  - libffi
  - libiconv
  - libgfortran
  - libpng
  - libprotobuf
  - libxml2
  - markdown
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - networkx
  - ninja
  - numpy
  - numpy-base
  - oauthlib
  - openbabel
  - openssl
  - pandas
  - pcre
  - pip
  - pixman
  - protobuf
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch=1.5.1
  - pytz
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scipy
  - seaborn
  - setuptools
  - six
  - sqlite
  - tensorboard
  - tensorboard-plugin-wit
  - tk
  - tornado
  - tqdm
  - urllib3
  - werkzeug
  - wheel
  - xz
  - zipp
  - zlib
  - gunicorn
  - flask
  - rdkit
  - pip:
    - conf
