name: rnamigos
channels:
  - pytorch
  - openbabel
  - dglteam
  - conda-forge
  - rdkit
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - biopython=1.76
  - blas=1.0
  - boost=1.63.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cairo=1.14.12
  - certifi=2020.12.5
  - click=7.0
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.3.0
  - dgl=0.4.3post2
  - expat=2.2.6
  - flask=1.0.2
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gunicorn=19.9.0
  - icu=58.2
  - intel-openmp=2020.1
  - itsdangerous=1.1.0
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - networkx=2.2
  - ninja=1.9.0
  - nox=1.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openbabel=2.4.1
  - openssl=1.1.1h
  - pandas=0.23.4
  - pcre=8.43
  - pillow=7.1.2
  - pip=20.0.2
  - pixman=0.38.0
  - pyparsing=2.3.0
  - pyqt=5.9.2
  - python=3.6.10
  - python-dateutil=2.7.5
  - python_abi=3.6
  - pytorch=1.5.0
  - pytz=2018.7
  - qt=5.9.7
  - rdkit=2017.09.1
  - readline=8.0
  - regex=2018.11.22
  - scipy=1.1.0
  - setuptools=47.1.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.31.1
  - tk=8.6.8
  - tornado=6.0.4
  - werkzeug=0.14.1
  - wheel=0.34.2
  - wrapt=1.10.11
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - flask
  - gunicorn
  - requests
