name: rnamigos
channels:
  - anaconda
  - bioconda
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.9.0
  - biopython=1.76
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=4.1.0
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - dgl=0.4.3post2
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.64.3
  - google-auth=1.17.2
  - google-auth-oauthlib=0.4.1
  - grpcio=1.27.2
  - icu=67.1
  - idna=2.9
  - importlib-metadata=1.6.1
  - intel-openmp=2019.4
  - kiwisolver=1.2.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libxml2=2.9.10
  - markdown=3.2.2
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.9.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - oauthlib=3.0.1
  - openbabel=3.1.1
  - openssl=1.1.1g
  - pandas=1.0.5
  - pcre=8.44
  - pip=20.1.1
  - pixman=0.38.0
  - protobuf=3.12.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.5.1
  - pytz=2020.1
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.2.0
  - rsa=4.6
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.2
  - tensorboard=2.2.2
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.46.1
  - urllib3=1.25.9
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - gunicorn=20.0.4
  - flask=1.1.2
  - rdkit
  - pip:
    - conf==0.4.1